name: Deploy to Azure Web App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./node-app
        run: npm install

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '0.15.4'

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Initialize Terraform
        run: terraform init

      - name: Deploy Azure Web App
        run: terraform apply -auto-approve
